import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdir, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { findChrome, launch } from './helpers/browser.mjs';
import { startTestServer } from './helpers/test-server.mjs';

test('priority filters share board/archive views, persist per project and preserve hidden tasks during keyboard reordering', { skip: !await findChrome(), timeout: 90000 }, async t => {
  const app = await startTestServer(t, { port: 0, executor: null, detector: async () => [] });
  t.diagnostic('Filter fixture server started.');
  const project = await app.board.createProject({ name: 'Filtered pipeline', workflowMode: 'pipeline' });
  const exact = '  Composer\r\n🐕 {{title}}  ';
  const first = await app.board.createTask({ projectId: project.id, title: 'Urgent first', priority: 4, prompt: exact });
  const hidden = await app.board.createTask({ projectId: project.id, title: 'Hidden low', priority: 1, prompt: exact });
  const second = await app.board.createTask({ projectId: project.id, title: 'Urgent second', priority: 4, prompt: exact });
  const archived = [];
  for (let n = 0; n < 8; n++) {
    const task = await app.board.createTask({ projectId: project.id, title: n === 0 ? 'Oldest urgent archive' : `Archive ${n}`, priority: n === 0 ? 4 : n === 7 ? 1 : 0 });
    await app.board.transition(task.id, { column: 'done', expectedRevision: task.revision }); archived.push(task);
  }
  const other = await app.board.createProject({ name: 'Other pipeline', workflowMode: 'pipeline' });
  const otherTask = await app.board.createTask({ projectId: other.id, title: 'Other low', priority: 1 });
  const original = await app.board.state();
  t.diagnostic('Filter tasks and archive fixture created.');
  const browser = await launch(); assert.ok(browser); t.after(() => browser.close());
  t.diagnostic('Filter browser launched.');
  await browser.send('Page.addScriptToEvaluateOnNewDocument', { source: `localStorage.setItem('promptboard.kanban.project',${JSON.stringify(project.id)});const fetchOriginal=window.fetch;window.__taskWrites=[];window.fetch=function(...args){if(/^\\/api\\/(tasks|projects)(?:\\/|$)/.test(args[0])&&args[1]?.method&&!['GET','HEAD'].includes(args[1].method))window.__taskWrites.push({url:args[0],body:JSON.parse(args[1].body||'{}')});return Reflect.apply(fetchOriginal,this,args);};` });
  const enter = async selector => { await browser.eval(`const e=document.querySelector(${JSON.stringify(selector)});e.scrollIntoView({block:'center'});e.focus();`);
    await browser.send('Input.dispatchKeyEvent', { type: 'keyDown', key: 'Enter', code: 'Enter', windowsVirtualKeyCode: 13, text: '\r' });
    await browser.send('Input.dispatchKeyEvent', { type: 'keyUp', key: 'Enter', code: 'Enter', windowsVirtualKeyCode: 13 }); };
  const select = async (id, value) => browser.eval(`const s=document.getElementById(${JSON.stringify(id)});s.value=${JSON.stringify(value)};s.dispatchEvent(new Event('change',{bubbles:true}));`);
  t.diagnostic('Filter browser initialization script registered.');
  await browser.goto(app.url + '/#/kanban'); await browser.until(`document.querySelector('[data-id="${first.id}"]')`, 'initial tasks');
  t.diagnostic('Filter initial tasks rendered.');
  for (const width of [1280, 390]) for (const theme of ['light', 'dark']) {
    t.diagnostic(`Filter layout ${width}/${theme}.`);
    await browser.resize(width, 900); await browser.eval(`document.documentElement.dataset.theme=${JSON.stringify(theme)};`);
    await select('board-priority-filter', 'all'); await browser.eval(`document.getElementById('board-priority-filter').focus();`); await browser.type('u');
    await browser.until(`document.getElementById('board-priority-filter').value==='4' && !document.querySelector('[data-id="${hidden.id}"]')`, 'native urgent filter');
    assert.deepEqual(await browser.eval(`return [...document.querySelectorAll('[data-column="todo"] .kanban-card')].map(e=>e.dataset.id);`), [first.id, second.id]);
    assert.ok(await browser.eval(`return !!document.querySelector('[data-id="${archived[0].id}"]');`), 'Oldest matching archive remains in the filtered preview.');
    assert.equal(await browser.eval(`return document.querySelector('[data-column="todo"] .kanban-column-count').textContent;`), '2/3');
    assert.equal(await browser.layout(`const r=document.getElementById('board-priority-filter').getBoundingClientRect();return r.width>0 && r.left>=0 && r.right<=innerWidth;`), true);
    if (process.env.PB_BROWSER_SHOTS) { await mkdir(process.env.PB_BROWSER_SHOTS, { recursive: true }); await writeFile(join(process.env.PB_BROWSER_SHOTS, `priority-filter-${width}-${theme}.png`), await browser.screenshot()); }
    await enter('[data-column="done"] .kanban-done-all'); await browser.until(`document.getElementById('done-dialog').open && document.querySelector('#archive-rows [data-archive-task="${archived[0].id}"]')`, 'filtered archive');
    assert.equal(await browser.eval(`return document.getElementById('archive-priority-filter').value;`), '4');
    assert.equal(await browser.eval(`return document.getElementById('archive-count').textContent;`), '1 of 8 tasks');
    await browser.eval(`document.getElementById('archive-filter').focus();`); await browser.type('no match');
    await browser.until(`!document.getElementById('archive-empty').hidden`, 'combined title and priority filter');
    await browser.eval(`const s=document.getElementById('archive-filter');s.value='';s.dispatchEvent(new Event('input',{bubbles:true}));document.getElementById('archive-priority-filter').focus();`); await browser.type('l');
    await browser.until(`document.getElementById('archive-priority-filter').value==='1' && document.querySelector('#archive-rows [data-archive-task="${archived[7].id}"]')`, 'shared Low filter');
    assert.equal(await browser.eval(`return document.getElementById('board-priority-filter').value;`), '1');
    assert.equal(await browser.layout(`const r=document.getElementById('archive-priority-filter').getBoundingClientRect();return r.width>0&&r.left>=0&&r.right<=innerWidth;`), true);
    if (process.env.PB_BROWSER_SHOTS) await writeFile(join(process.env.PB_BROWSER_SHOTS, `priority-filter-archive-${width}-${theme}.png`), await browser.screenshot());
    await enter('#done-dialog-close'); await browser.until(`!document.getElementById('done-dialog').open`, 'archive closed');
  }
  assert.deepEqual(await app.board.state(), original, 'Filtering must make no saved task/configuration changes.');
  assert.deepEqual(await browser.eval('return window.__taskWrites;'), []);
  await select('board-priority-filter', '2'); assert.equal(await browser.eval(`return document.getElementById('board-priority-filter-summary').textContent;`), 'No tasks match this priority.');
  await select('board-priority-filter', '4');
  await enter(`[data-id="${second.id}"] .kanban-more-toggle`); await enter(`[data-id="${second.id}"] .kanban-move-up`);
  await browser.until(`document.querySelector('[data-column="todo"] .kanban-card')?.dataset.id===${JSON.stringify(second.id)} && !document.querySelector('.kanban-card.pending')`, 'filtered keyboard move');
  const reordered = (await app.board.state()).projects.find(p => p.id === project.id).tasks.filter(task => task.column === 'todo');
  assert.deepEqual(reordered.map(task => task.id), [second.id, first.id, hidden.id]);
  assert.ok(reordered.every(task => task.prompt === exact));
  assert.equal(await browser.eval(`return window.__taskWrites.at(-1).body.index;`), 0);
  await browser.eval(`const source=document.querySelector('[data-id="${second.id}"]'),target=document.querySelector('[data-id="${first.id}"]'),transfer=new DataTransfer();source.dispatchEvent(new DragEvent('dragstart',{bubbles:true,dataTransfer:transfer}));target.dispatchEvent(new DragEvent('drop',{bubbles:true,cancelable:true,dataTransfer:transfer}));source.dispatchEvent(new DragEvent('dragend',{bubbles:true,dataTransfer:transfer}));`);
  await browser.until(`!document.querySelector('.kanban-card.pending')`, 'filtered drop settled');
  assert.deepEqual((await app.board.state()).projects.find(p => p.id === project.id).tasks.filter(task => task.column === 'todo').map(task => task.id), [second.id, first.id, hidden.id]);
  await select('project-select', other.id); await browser.until(`document.querySelector('[data-id="${otherTask.id}"]')`, 'other project');
  assert.equal(await browser.eval(`return document.getElementById('board-priority-filter').value;`), 'all');
  await select('board-priority-filter', '1'); await select('project-select', project.id);
  await browser.until(`document.getElementById('board-priority-filter').value==='4'`, 'original project filter retained');
  await browser.reload(); await browser.until(`document.getElementById('board-priority-filter').value==='4' && document.querySelector('[data-id="${second.id}"]')`, 'filter retained on reload');
  await enter('#view-timeline'); await browser.until(`!document.getElementById('timeline').hidden`, 'timeline view');
  assert.equal(await browser.eval(`return document.getElementById('board-priority-filter-field').hidden;`), true);
  assert.equal(await browser.eval(`return document.getElementById('board-count').textContent;`), '11');
  await enter('#view-board'); await browser.until(`!document.getElementById('board-priority-filter-field').hidden`, 'board filter restored');
  assert.deepEqual((await app.board.state()).runs, []); assert.deepEqual((await app.board.state()).sessions, []);
  assert.deepEqual(browser.consoleMessages.filter(message => message.startsWith('EXCEPTION')), []);
});

test('older capabilities and malformed saved filters never hide cards or expose unsupported priority controls', { skip: !await findChrome(), timeout: 60000 }, async t => {
  const app = await startTestServer(t, { port: 0, executor: null, detector: async () => [] });
  t.diagnostic('Older filter fixture server started.');
  const project = await app.board.createProject({ name: 'Older filter server', workflowMode: 'pipeline' });
  const task = await app.board.createTask({ projectId: project.id, title: 'Visible None' });
  const archived = await app.board.createTask({ projectId: project.id, title: 'Visible completed' }); await app.board.transition(archived.id, { column: 'done', expectedRevision: archived.revision });
  const browser = await launch(); assert.ok(browser); t.after(() => browser.close());
  t.diagnostic('Older filter browser launched.');
  await browser.send('Page.addScriptToEvaluateOnNewDocument', { source: `localStorage.setItem('promptboard.priority-filter.${project.id}','4');const nativeFetch=window.fetch;window.fetch=async function(...args){const r=await Reflect.apply(nativeFetch,this,args);if(args[0]!=='/api/session')return r;const d=await r.json();delete d.capabilities.taskPriority;return new Response(JSON.stringify(d),{status:r.status,headers:r.headers});};` });
  await browser.goto(app.url + '/#/kanban'); await browser.until(`document.querySelector('[data-id="${task.id}"]')`, 'older visible card');
  t.diagnostic('Older filter tasks rendered.');
  assert.equal(await browser.eval(`return document.getElementById('board-priority-filter-field').hidden;`), true);
  await browser.eval(`document.querySelector('[data-column="done"] .kanban-done-all').click();`); await browser.until(`document.getElementById('done-dialog').open`, 'older archive');
  assert.equal(await browser.eval(`return document.getElementById('archive-priority-field').hidden;`), true);
  assert.ok(await browser.eval(`return !!document.querySelector('#archive-rows [data-archive-task="${archived.id}"]');`));
  await browser.send('Page.addScriptToEvaluateOnNewDocument', { source: `localStorage.setItem('promptboard.priority-filter.${project.id}','invalid');window.fetch=async function(...args){return Reflect.apply(nativeFetch,this,args);};` });
  await browser.reload(); await browser.until(`document.querySelector('[data-id="${task.id}"]')`, 'malformed filter fallback');
  assert.equal(await browser.eval(`return document.getElementById('board-priority-filter').value;`), 'all');
  assert.deepEqual((await app.board.state()).runs, []);
});
